#!/bin/bash

program-installed() {
    which "$1" &> /dev/null
    rc=$?
    if [[ $rc -ne 0 ]]; then
        return $rc
    fi
    return 0
}

check_uid() {
    if [[ $(id -u) -ne 0 ]]; then
        echo "Must be ran as root"
        exit
    fi
}

check_uid
if ! program-installed rsync ; then
    if program-installed yum ; then 
        yum -y install rsync 
    elif program-installed apt-get ; then
        apt-get -y install rsync
    fi
fi

if [[ -d /usr/local/bin/ ]]; then
    rsync -a bin/ /usr/local/bin/ &> /dev/null
    if [[ $? -eq 0 ]]; then
        echo "Bins successfully installed"
    else
	echo "Error installing bins" 1>&2
    fi
   	
fi
